---

version: "3"

services:
  store:
    build:
      context: .
      dockerfile: Dockerfile-development
    volumes:
      - ./assets/scripts:/opt/app/assets/scripts
      - ./assets/static:/opt/app/assets/static
      - ./assets/styles:/opt/app/assets/styles
      - ./config:/opt/app/config
      - ./lib:/opt/app/lib
      - ./priv:/opt/app/priv
    environment:
      - MIX_ENV
    command: mix phx.server
    working_dir: /opt/app
    network_mode: host
